### ISSUE TITLE
Unknown Email

### ISSUE THREAD

**Issue by phase** [Killazombiecow/TrintonCore#1]
They email you're using on your local git client isn't registered with your GitHub account, so it is showing as a blank account.Go to your settings to add it.

**Comment by Killazombiecow** [comment]
Should be fixed now

**Comment by phase** [comment]
I still shows up as a blank one on the main page, but if you go into https://github.com/Killazombiecow/TrintonCore/commits/master it shows your **face**.

**Comment by phase** [comment]
Yeah, it's working now. :3
